import os
import pdfplumber
from docx import Document

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS


class DocumentProcessor:
    def __init__(self):
        # Lightweight embedding model (good quality + fast)
        self.embeddings = HuggingFaceEmbeddings(
            model_name="sentence-transformers/all-MiniLM-L6-v2"
        )

        # Smart chunking
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=800,
            chunk_overlap=100
        )

    def extract_text(self, file_path):
        """
        Extract text from PDF or DOCX file
        """
        # Streamlit `uploaded_file` is a buffer with a .name attribute, not
        # a filesystem path.  Accept either a path string or a file-like
        # object.  Determine the extension from the filename when possible.
        filename = getattr(file_path, "name", None)
        if filename:
            ext = os.path.splitext(filename)[1].lower()
        elif isinstance(file_path, str):
            ext = os.path.splitext(file_path)[1].lower()
        else:
            ext = None

        if ext == ".pdf":
            return self._extract_pdf(file_path)
        elif ext == ".docx":
            return self._extract_docx(file_path)
        else:
            raise ValueError("Unsupported file format. Use PDF or DOCX.")

    def _extract_pdf(self, file_path):
        text = ""
        # pdfplumber.open accepts both path strings and file-like objects
        # containing PDF data, which covers the Streamlit upload case.
        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() or ""
        return text

    def _extract_docx(self, file_path):
        doc = Document(file_path)
        return "\n".join([para.text for para in doc.paragraphs])

    def create_vector_store(self, text):
        """
        Split text → Create embeddings → Store in FAISS
        """
        # `text` may be a list of pre-split chunks (as used by the Streamlit
        # app) or a raw string.  Accept both for backwards compatibility.
        if isinstance(text, list):
            chunks = text
        else:
            chunks = self.text_splitter.split_text(text)

        vector_store = FAISS.from_texts(
            texts=chunks,
            embedding=self.embeddings
        )

        return vector_store

    def chunk_text(self, text):
        """Return a list of text chunks generated by the splitter."""

        return self.text_splitter.split_text(text)